In [136]:
import pandas as pd

In [137]:
df = pd.read_csv('idsc_train.csv')

In [138]:
colunas = ['dt_dep', 'dt_arr','hora_ref', 'hora_esperas', 'hora_metar', 'hora_metaf', 'hora_tcp']

# 1. Converter as colunas para datetime de uma s√≥ vez
df[colunas] = df[colunas].apply(pd.to_datetime)

In [139]:
df['duracao'] = (df['dt_arr']-df['dt_dep']).dt.total_seconds()
df.head(2).T

,0,1
flightid,2127312fea57d093815e49b5aefee46d,e20845be25ed24b87131066d865cd9bc
origem,SBBR,SBFL
destino,SBGL,SBSP
dt_dep,2022-06-01 08:08:46,2022-06-01 09:12:29
dt_arr,2022-06-01 09:27:43,2022-06-01 10:01:07
hora_ref,2022-06-01 08:00:00,2022-06-01 09:00:00
esperas,0,0
hora_esperas,2022-06-01 07:00:00,2022-06-01 08:00:00
aero_esperas,SBGL,SBSP
hora_metaf,2022-06-01 09:00:00,2022-06-01 10:00:00
metaf,METAF SBGL 011200Z 15002KT 2000 BR BKN033...,METAF SBSP 011300Z 07004KT 4000 BR OVC033 ...
aero_metaf,SBGL,SBSP
hora_metar,2022-06-01 08:00:00,2022-06-01 09:00:00
metar,METAR SBGL 011100Z 10003KT 070V130 7000 FEW009...,METAR SBSP 011200Z 08003KT 030V130 9999 -RA SC...
aero_metar,SBGL,SBSP
hora_tcp,2022-06-01 09:00:00,2022-06-01 10:00:00
troca,0,0
aero_tcp,SBGL,SBSP
duracao,4737.0,2918.0

In [140]:
df.drop(colunas, axis=1, inplace=True)

In [141]:
df.head(2).T

,0,1
flightid,2127312fea57d093815e49b5aefee46d,e20845be25ed24b87131066d865cd9bc
origem,SBBR,SBFL
destino,SBGL,SBSP
esperas,0,0
aero_esperas,SBGL,SBSP
metaf,METAF SBGL 011200Z 15002KT 2000 BR BKN033...,METAF SBSP 011300Z 07004KT 4000 BR OVC033 ...
aero_metaf,SBGL,SBSP
metar,METAR SBGL 011100Z 10003KT 070V130 7000 FEW009...,METAR SBSP 011200Z 08003KT 030V130 9999 -RA SC...
aero_metar,SBGL,SBSP
troca,0,0
aero_tcp,SBGL,SBSP
duracao,4737.0,2918.0

In [142]:
from geopy.distance import geodesic

# Coordenadas dos aeroportos (latitude, longitude)
coordenadas = {
    'SBBR': (-15.8697, -47.9207),  # Bras√≠lia
    'SBFL': (-27.6703, -48.5525),  # Florian√≥polis
    'SBCT': (-25.5282, -49.1758),  # Curitiba
    'SBRJ': (-22.9102, -43.1631),  # Rio de Janeiro (Santos Dumont)
    'SBCF': (-19.6328, -43.9634),  # Belo Horizonte (Confins)
    'SBPA': (-29.9936, -51.1770),  # Porto Alegre
    'SBSP': (-23.6261, -46.6566),  # S√£o Paulo (Congonhas)
    'SBRF': (-8.1264, -34.9240),   # Recife
    'SBSV': (-12.9105, -38.3311),  # Salvador
    'SBKP': (-23.0074, -47.1345),  # Campinas (Viracopos)
    'SBGR': (-23.4322, -46.4695),  # S√£o Paulo (Guarulhos)
    'SBGL': (-22.8076, -43.2506)   # Rio de Janeiro (Gale√£o)
}

# Calcular dist√¢ncia entre todos os pares de aeroportos
for aeroporto1 in coordenadas:
    for aeroporto2 in coordenadas:
        if aeroporto1 != aeroporto2:
            distancia = geodesic(coordenadas[aeroporto1], coordenadas[aeroporto2]).kilometers

In [143]:
def distancia(row):
     return geodesic(coordenadas[row['origem']], coordenadas[row['destino']]).kilometers

df['distancia'] = df.apply(distancia, axis=1)
df

,flightid,origem,destino,esperas,aero_esperas,metaf,aero_metaf,metar,aero_metar,troca,aero_tcp,duracao,distancia
0,2127312fea57d093815e49b5aefee46d,SBBR,SBGL,0,SBGL,METAF SBGL 011200Z 15002KT 2000 BR BKN033...,SBGL,METAR SBGL 011100Z 10003KT 070V130 7000 FEW009...,SBGL,0,SBGL,4737.0,911.166170
1,e20845be25ed24b87131066d865cd9bc,SBFL,SBSP,0,SBSP,METAF SBSP 011300Z 07004KT 4000 BR OVC033 ...,SBSP,METAR SBSP 011200Z 08003KT 030V130 9999 -RA SC...,SBSP,0,SBSP,2918.0,486.770907
2,79ffad2c4f0b8f0d6a25977140daf9a9,SBCT,SBSP,0,SBSP,METAF SBSP 011300Z 07004KT 4000 BR OVC033 ...,SBSP,METAR SBSP 011200Z 08003KT 030V130 9999 -RA SC...,SBSP,0,SBSP,2712.0,330.898357
3,2b846c207720b4eb92a3da158ac6cf68,SBCT,SBSP,0,SBSP,METAF SBSP 011300Z 07004KT 4000 BR OVC033 ...,SBSP,METAR SBSP 011200Z 08003KT 030V130 9999 -RA SC...,SBSP,0,SBSP,2748.0,330.898357
4,f51e68eeabfa16c625e7454a8974333e,SBRJ,SBSP,0,SBSP,METAF SBSP 011300Z 07004KT 4000 BR OVC033 ...,SBSP,METAR SBSP 011200Z 08003KT 030V130 9999 -RA SC...,SBSP,0,SBSP,2678.0,366.126382
...,...,...,...,...,...,...,...,...,...,...,...,...,...
152430,9ff5febb9d79c517679bf20050066027,SBPA,SBKP,0,SBKP,METAF SBKP 131400Z 12006KT CAVOK 19/10 Q1020=\n,SBKP,METAR SBKP 131300Z 13011KT CAVOK 18/10 Q1021=,SBKP,0,SBKP,4878.0,872.461572
152431,49681283735fdda95885adaebdad245e,SBRJ,SBBR,0,SBBR,METAF SBBR 131700Z 18003KT CAVOK 27/11 Q1014=\n,SBBR,METAR SBBR 131600Z 14003KT 9999 FEW040 26/14 Q...,SBBR,0,SBBR,5202.0,925.595955
152432,0ea8f882431d6fbe1f431a0593bbf54d,SBKP,SBBR,0,SBBR,METAF SBBR 131700Z 18003KT CAVOK 27/11 Q1014=\n,SBBR,METAR SBBR 131600Z 14003KT 9999 FEW040 26/14 Q...,SBBR,0,SBBR,4501.0,794.426702
152433,b4251c41bdc3e827ec18c89a40bbd45c,SBGR,SBGL,0,SBGL,METAF SBGL 132100Z 16006KT 9999 OVC033 ...,SBGL,METAR SBGL 132000Z 14008KT 9999 SCT023 BKN040 ...,SBGL,0,SBGL,2229.0,336.886260
152434,f7e7a2104137d2d6b9bd89ba2ab9a433,SBRF,SBGL,0,SBGL,METAF SBGL 132200Z 15005KT 9999 OVC033 ...,SBGL,METAR SBGL 132100Z 13006KT 9999 SCT023 BKN040 ...,SBGL,0,SBGL,9598.0,1852.647674

In [144]:
from metar import Metar

- temp
- vis
- max_vis
- wind_speed
- wind_gust
- dewpt
- press
- wind_speed_peak
- press_sea_level
- precip_1hr

In [160]:
def download(row, met, tipo):
    meta = row[tipo]
    if tipo == 'metaf':
        meta = meta.replace('METAF', 'METAR').split('\n')[0]

    obs = Metar.Metar(meta)
    metodo = getattr(obs, met, None)
    if metodo == None:
        print(f'Id: {row.flightid}\nParametro: {met}')
        return 0
    return metodo.value()

def extracao_meta(df, tipo = 'metar'):
    sufixo = '_'+ tipo
    dados = [
    "temp",
    "vis",
    "wind_speed",
    "dewpt",
    "press",
    ]
    for met in dados:
        df[met+sufixo] = df.apply(download, axis=1, args=(met,tipo,))

    return df.copy()

In [154]:
train = extracao_meta(df, 'metar')

1b6a0449ff56f8db04cd97e005f6482f
 press

In [155]:
train.head(1).T

                                                                  0
flightid                           2127312fea57d093815e49b5aefee46d
origem                                                         SBBR
destino                                                        SBGL
esperas                                                           0
aero_esperas                                                   SBGL
metaf             METAF SBGL 011200Z  15002KT 2000     BR BKN033...
aero_metaf                                                     SBGL
metar             METAR SBGL 011100Z 10003KT 070V130 7000 FEW009...
aero_metar                                                     SBGL
troca                                                             0
aero_tcp                                                       SBGL
duracao                                                      4737.0
distancia                                                 911.16617
temp_metar                                                     23.0
vis_metar                                                    7000.0
wind_speed_metar                                                3.0
dewpt_metar                                                    21.0
press_metar                                                  1016.0

### TEste

In [173]:
from datetime import datetime, timedelta

In [174]:
test = pd.read_csv('idsc_test.csv')

In [175]:
colunas = ['dt_dep', 'hora_ref', 'hora_esperas', 'hora_metar', 'hora_metaf', 'hora_tcp']

# 1. Converter as colunas para datetime de uma s√≥ vez
test[colunas] = test[colunas].apply(pd.to_datetime)

# 2. Encontrar √≠ndices de linhas com 'hora_metaf' nula
null_indices = test.index[test['hora_metaf'].isna()]

# 3. Atualizar as colunas com base nas colunas 'hora_metar' e 'metar'
test.loc[null_indices, 'hora_metaf'] = test.loc[null_indices, 'hora_metar'] + timedelta(hours=1)
test.loc[null_indices, 'metaf'] = test.loc[null_indices, 'metar']
test.loc[null_indices, 'aero_metaf'] = test.loc[null_indices, 'aero_metar']

# 4. Converter as colunas para valores inteiros UNIX timestamp
# df[colunas] = df[colunas].apply(lambda x: x.dt.timestamp()).astype(int)

In [176]:
test = extracao_meta(test, 'metar')

In [177]:
test.head(1).T

                                                                  0
flightid                           7945735584a3297121c4f5ae0de8ecd1
origem                                                         SBKP
destino                                                        SBSV
dt_dep                                          2023-05-30 11:36:03
hora_ref                                        2023-05-30 11:00:00
snapshot_radar    MULTIPOINT ((-0.8807200448127578 -0.5148453155...
path              http://satelite.cptec.inpe.br/repositoriogoes/...
hora_esperas                                    2023-05-30 10:00:00
esperas                                                           0
aero_esperas                                                   SBSV
hora_metaf                                      2023-05-30 12:00:00
metaf             METAR SBSV 301100Z 12009KT 9999 FEW023 28/21 Q...
aero_metaf                                                     SBSV
hora_metar                                      2023-05-30 11:00:00
metar             METAR SBSV 301100Z 12009KT 9999 FEW023 28/21 Q...
aero_metar                                                     SBSV
hora_tcp                                        2023-05-30 12:00:00
troca                                                             0
aero_tcp                                                       SBSV
hora_tcr                                                        NaN
aero_tcr                                                        NaN
temp_metar                                                     28.0
vis_metar                                                   10000.0
wind_speed_metar                                                9.0
dewpt_metar                                                    21.0
press_metar                                                  1019.0

In [183]:
extracao_meta(test, 'metaf').head(1).T

                                                                  0
flightid                           7945735584a3297121c4f5ae0de8ecd1
origem                                                         SBKP
destino                                                        SBSV
dt_dep                                          2023-05-30 11:36:03
hora_ref                                        2023-05-30 11:00:00
snapshot_radar    MULTIPOINT ((-0.8807200448127578 -0.5148453155...
path              http://satelite.cptec.inpe.br/repositoriogoes/...
hora_esperas                                    2023-05-30 10:00:00
esperas                                                           0
aero_esperas                                                   SBSV
hora_metaf                                      2023-05-30 12:00:00
metaf             METAR SBSV 301100Z 12009KT 9999 FEW023 28/21 Q...
aero_metaf                                                     SBSV
hora_metar                                      2023-05-30 11:00:00
metar             METAR SBSV 301100Z 12009KT 9999 FEW023 28/21 Q...
aero_metar                                                     SBSV
hora_tcp                                        2023-05-30 12:00:00
troca                                                             0
aero_tcp                                                       SBSV
hora_tcr                                                        NaN
aero_tcr                                                        NaN
temp_metar                                                     28.0
vis_metar                                                   10000.0
wind_speed_metar                                                9.0
dewpt_metar                                                    21.0
press_metar                                                  1019.0
temp_metaf                                                     28.0
vis_metaf                                                   10000.0
wind_speed_metaf                                                9.0
dewpt_metaf                                                    21.0
press_metaf                                                  1019.0